--CREATE DATABASE DDS_TH
--GO
--USE DDS_TH
--GO
CREATE TABLE NAM
(
	ID_NAM INT IDENTITY(1,1),
	NAM VARCHAR(4),
	CONSTRAINT PK_N PRIMARY KEY(ID_NAM)
)
GO

CREATE TABLE THANG_TRONG_NAM
(
	ID_TTN INT IDENTITY(1,1),
	THANG VARCHAR(2),
	QUY VARCHAR(1),
	ID_NAM INT,
	CONSTRAINT PK_TTN PRIMARY KEY(ID_TTN)
)
GO

CREATE TABLE NGAY_TRONG_THANG
(
	ID_NTT INT IDENTITY(1,1),
	NGAY VARCHAR(2),
	ID_TTN INT,
	CONSTRAINT PK_NTT PRIMARY KEY(ID_NTT)
)
GO

CREATE TABLE DIM_PHU
(
	ID INT IDENTITY(1,1),
	PHU_ID VARCHAR(255),
	PHU VARCHAR(255),
	PHU_GROUP VARCHAR(200),
	CITY VARCHAR(255),
	POSTALCODE VARCHAR(255),
	WEBSITE VARCHAR(255),
	LATITUDE FLOAT,
	LONGITUDE FLOAT,
	CONSTRAINT PK_P PRIMARY KEY(ID)
)
GO

CREATE TABLE DIM_VACCINES_BY_AGE
(
	VACCINES_BY_AGE_ID INT IDENTITY(1,1),
	DATE DATE,
	PHU_ID VARCHAR(255),
	AGE_GROUP_ID INT,
	AT_LEAST_ONE_DOSE_CUMULATIVE INT,
	SECOND_DOSE_CUMULATIVE INT,
	FULLY_VACCINATED_CUMULATIVE INT,
	THIRD_DOSE_CUMULATIVE INT,
	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	CONSTRAINT PK_VBA PRIMARY KEY(VACCINES_BY_AGE_ID)
)
GO

CREATE TABLE DIM_ONGOING_OUTBREAK_PHU
(
	ONGOING_OUTBREAK_PHU_ID INT IDENTITY(1,1),
	DATE DATE,
	PHU_NUM VARCHAR(255),
	OUTBREAK_GROUP VARCHAR(150),
	NUMBER_ONGOING_OUTBREAKS INT,
	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	CONSTRAINT PK_OOP PRIMARY KEY(ONGOING_OUTBREAK_PHU_ID)
)
GO

CREATE TABLE DIM_AGE_GROUP
(
	AGE_GROUP_ID INT IDENTITY(1,1),
	AGE_GROUP_TYPE VARCHAR(200),
	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	CONSTRAINT PK_AG PRIMARY KEY(AGE_GROUP_ID)
)
GO

CREATE TABLE DIM_CASE_REPORT
(
	CASE_REPORT_ID INT IDENTITY(1,1),
	OUTCOME VARCHAR(255),
	GENDER VARCHAR(255),
	REPORTING_PHU_ID VARCHAR(255),
	SPECIMEN_DATE DATE,
	TEST_REPORTED_DATE DATE,
	CASE_ACQUISITION_INFO VARCHAR(255),
	ACCURATE_EPISODE_DT DATE,
	OUTBREAK_RELATED VARCHAR(255),
	AGE_ID INT,
	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	CONSTRAINT PK_CR PRIMARY KEY(CASE_REPORT_ID)
)
GO

CREATE TABLE FACT_CASE
(
	ID_CASE INT IDENTITY(1,1),
	ID_NGAY INT,
	ID_PHU INT,
	ID_AGE_GROUP INT,
	ID_VACCINES_BY_AGE INT,
	ID_ONGOING_OUTBREAK_PHU INT,
	ID_CASE_REPORT INT,
	GENDER VARCHAR(255),
	OUTCOME VARCHAR(255),
	PROVINCE VARCHAR(255),
	EXPOSURE VARCHAR(255),
	CONSTRAINT PK_FC PRIMARY KEY(ID_CASE)
)
GO