--CREATE DATABASE DDS_TH
--GO
USE DDS_TH
GO
CREATE TABLE NAM
(
	ID_NAM INT IDENTITY(1,1),
	NAM VARCHAR(4),
	CONSTRAINT PK_N PRIMARY KEY(ID_NAM)
)
GO

CREATE TABLE THANG_TRONG_NAM
(
	ID_TTN INT IDENTITY(1,1),
	THANG VARCHAR(2),
	QUY VARCHAR(1),
	ID_NAM INT,
	CONSTRAINT PK_TTN PRIMARY KEY(ID_TTN)
)
GO

CREATE TABLE NGAY_TRONG_THANG
(
	ID_NTT INT IDENTITY(1,1),
	NGAY VARCHAR(2),
	ID_TTN INT,
	CONSTRAINT PK_NTT PRIMARY KEY(ID_NTT)
)
GO

CREATE TABLE DIM_PHU
(
	ID INT IDENTITY(1,1),
	PHU_ID INT,
	PHU NVARCHAR(MAX),
	PHU_GROUP NVARCHAR(200),
	CITY NVARCHAR(MAX),
	POSTALCODE NVARCHAR(MAX),
	WEBSITE NVARCHAR(MAX),
	LATITUDE FLOAT,
	LONGITUDE FLOAT,
	CONSTRAINT PK_P PRIMARY KEY(ID)
)
GO

CREATE TABLE DIM_VACCINES_BY_AGE
(
	VACCINES_BY_AGE_ID INT IDENTITY(1,1),
	DATE DATE,
	PHU_ID INT,
	AGE_GROUP_ID INT,
	AT_LEAST_ONE_DOSE_CUMULATIVE INT,
	SECOND_DOSE_CUMULATIVE INT,
	FULLY_VACCINATED_CUMULATIVE INT,
	THIRD_DOSE_CUMULATIVE INT,
	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	CONSTRAINT PK_VBA PRIMARY KEY(VACCINES_BY_AGE_ID)
)
GO

CREATE TABLE DIM_ONGOING_OUTBREAK_PHU
(
	ONGOING_OUTBREAK_PHU_ID INT IDENTITY(1,1),
	DATE DATE,
	PHU_NUM INT,
	OUTBREAK_GROUP VARCHAR(150),
	NUMBER_ONGOING_OUTBREAKS INT,
	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	CONSTRAINT PK_OOP PRIMARY KEY(ONGOING_OUTBREAK_PHU_ID)
)
GO

CREATE TABLE DIM_COMPILED_CASE_DETAILS
(
	ID INT IDENTITY(1,1),
	OBJECT_ID INT,
	ROW_ID INT,
	DATE_REPORTED DATETIME,
	PHU_ID INT,
	AGE_GROUP_ID INT,
	GENDER VARCHAR(MAX),
	EXPOSURE VARCHAR(MAX),
	CASE_STATUS VARCHAR(MAX),
	PROVINCE VARCHAR(MAX),
	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	CONSTRAINT PK_CCD PRIMARY KEY(ID)
)
GO

CREATE TABLE DIM_AGE_GROUP
(
	AGE_GROUP_ID INT IDENTITY(1,1),
	AGE_GROUP_TYPE NVARCHAR(200),
	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	CONSTRAINT PK_AG PRIMARY KEY(AGE_GROUP_ID)
)
GO

CREATE TABLE DIM_CASE_REPORT
(
	CASE_REPORT_ID INT IDENTITY(1,1),
	OUTCOME NVARCHAR(MAX),
	GENDER NVARCHAR(MAX),
	REPORTING_PHU_ID INT,
	SPECIMEN_DATE DATE,
	TEST_REPORTED_DATE DATE,
	CASE_ACQUISITION_INFO NVARCHAR(MAX),
	ACCURATE_EPISODE_DT DATE,
	OUTBREAK_RELATED NVARCHAR(MAX),
	AGE_ID INT,
	CREATED_DATE DATETIME,
	UPDATED_DATE DATETIME,
	CONSTRAINT PK_CR PRIMARY KEY(CASE_REPORT_ID)
)
GO

CREATE TABLE FACT_CASE
(
	ID_CASE INT IDENTITY(1,1),
	ID_NGAY INT,
	ID_PHU INT,
	ID_AGE_GROUP INT,
	ID_VACCINES_BY_AGE INT,
	ID_ONGOING_OUTBREAK_PHU INT,
	ID_COMPILED_CASE_DETAILS INT,
	ID_CASE_REPORT INT,
	GENDER NVARCHAR(MAX),
	OUTCOME NVARCHAR(MAX),
	PROVINCE NVARCHAR(MAX),
	CONSTRAINT PK_FC PRIMARY KEY(ID_CASE)
)
GO