select f.ID_CASE, P.CITY, C.DATE_REPORTED, A.AGE_GROUP_TYPE, C.EXPOSURE, f.INFECTED, f.DECEASED into mining_1
from DIM_PHU as P, DIM_AGE_GROUP as A, DIM_COMPILED_CASE_DETAILS as C, FACT_CASE as F
where f.ID_AGE_GROUP = a.ID and f.ID_COMPILED_CASE_DETAILS = c.ID and f.ID_PHU = p.ID
